In [1]:
# setup
import os
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables from both .env and shell
load_dotenv()  # This adds .env variables to os.environ

def create_engine_with_params(db_params: dict) -> create_engine:
    """Create SQLAlchemy engine using database parameters."""
    url = f"postgresql://{db_params['user']}:{db_params['password']}@{db_params['host']}:{db_params['port']}/{db_params['dbname']}"
    return create_engine(url)

db_params = {
    "dbname": "postgres", 
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD"),
    "host": os.getenv("DB_HOST"),
    "port": "5432"  # Default port for PostgreSQL
}

engine = create_engine_with_params(db_params)

In [5]:
data = pd.read_sql("select * from events", engine)
data.shape

(279, 6)

In [6]:
# no traffic since March 3rd
data.tail()

,event_id,timestamp,session_id,type,data,metadata
274,ba01d83a-b142-4707-9742-1abee4eb02bb,2025-03-04 22:39:33.421707+00:00,fc4876db-9e5c-42c3-87ad-b101b43e3d74,meme_created,{'input': 'Going to coffee with Geoff is one o...,"{'environment': 'development', 'timestamp_utc'..."
275,7d4af8e2-b5e2-440a-8178-15964447a995,2025-03-04 22:39:51.678371+00:00,fc4876db-9e5c-42c3-87ad-b101b43e3d74,meme_created,{'input': 'Going to coffee with Geoff is one o...,"{'environment': 'development', 'timestamp_utc'..."
276,47773ca6-3a07-449f-9817-22005b350632,2025-03-04 22:39:56.759315+00:00,fc4876db-9e5c-42c3-87ad-b101b43e3d74,meme_created,{'input': 'Going to coffee with Geoff is one o...,"{'environment': 'development', 'timestamp_utc'..."
277,0610f5aa-dcbe-411a-a509-8bced5b87442,2025-03-04 22:43:33.250529+00:00,fb2ab88d-efbb-4c55-8e25-649ac3aba7a0,meme_created,{'input': 'Going to coffee with Geoff is one o...,"{'environment': 'development', 'timestamp_utc'..."
278,6b7f260f-f576-444e-8fe8-58c6ad5674ec,2025-03-04 22:51:33.204915+00:00,c82efa33-071e-4443-a087-d201ed4ded47,meme_created,{'input': 'Going to coffee with Geoff is fun c...,"{'environment': 'development', 'timestamp_utc'..."

In [7]:
data.to_csv("gradio_app_raw_data.csv", index_label='event_id')

In [3]:
# only one table
pd.read_sql(
    """SELECT table_name 
FROM information_schema.tables
WHERE table_schema = 'public';""",
    engine)

  table_name
0     events